== Choice of api/API teams recommendation
=== pygeoapi
The API team have completed a POC investigation in to the use of https://pygeoapi.io/[pygeoapi]. In this investigation the team have investigated the viability and complexity of using pygeoapi the deliver the EDR and OGC Records endpoints for E-SOH. The code for this work can be found at https://github.com/EURODEO/e-soh-api/tree/ogc-records-provider[github].

One of the major hurdles faced when using pygeoapi in this POC investigation is the lack of documentation available for pygeoapi. Pygeoapi is still in an pre-v1 development stage. Some features are not documented properly, while others are documented but not implemented.

Pygeoapi is an OGC reference implementation, most endpoints defined by OGC have parameter parsing and other rules implemented. For us, the user, we only need to configure the endpoints and choose the data provider. Pygeoapi have implemented a plugin architecture where the user can choose between pre-made plugins for different data sources, or you can write a custom one. If we where going to use one of the provider plugins provided, the datastore would have needed to plan for this in the early stages of development, as format of the data source are quite rigid. Even if the datastore did plan for using pygeoapi, there are not any suitable provider for the time series data we have in E-SOH. There are no provider created for a gRPC service, and we will need to create our own provider for both EDR and OGC Records. This would most likely be true for any data source chosen EDR, as the ones in pygeoapi are very limited.

Pygeoapi accepts 4 different types of plugins. The provider and formatter plugins are relevant for this project. There are nothing special about the provider plugins in regards to pygeoapi. The provider pulls data from some data source and returns the data back in to the pygeoapi framework. We, the api team, are in agreement that any provider written for pygeoapi can be brought over to any other api solution where is could solve the same purpose. Pygeoapi does put some restrictions on the type returned from the provider plugin to the pygeoapi framework. This will lead to some overhead, and make us unable to use some internal format in the api.

The formatter plugins are suppose to provide custom export formats from pygeoapi. There are implemented some mechanisms to choose a format, but currently there are not ways to load any formatter plugins. This leads to having to edit the source code, and essentially having to fork pygeoapi, to load formatters. This leads to having to keep a fork up to date when new versions of pygeoapi are released.

In conclusion pygeoapi is mostly a configurable wrapper around a python web server, in this POC we used flask, but django also seems to be available. The pygeoapi developers have so far mostly focused on providing a framework around a OGC Features endpoints, and seems to serve static data well. E-SOH does not have static data, nor is gRPC a supported provider. By using pygeoapi we gain the parsing of parameters for OGC APIs, but loose control of internal process and object handling. In the eyes of the API team, there are not enough gains in using pygeoapi for creating the EDR and OGC Records APIs. Most of the code needed have to be written by the API team, and then shoehorned in to the pygeoapi framework. This makes pygeoapi like a black box where we are not resilient to changes. From a maintenance perspective, this leads to more complexity and the need to understand both the code written for gRPC data fetching and how internal process in pygeoapi work. The API team concludes and recommend to not continue use of pygeoapi API but rather build the entire solution in a pure API framework like fastAPI.
